/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

//import MiniFrames.*;
import default_package.DBConnection;
import default_package.Time;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.NumberFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo-x130
 */
public class Dashboard extends javax.swing.JFrame {

    // Gets the window's screen position
    int xx, xy;

    //Global variable for Hover Effect
    Color mouseEnterColor = new Color(255, 153, 0);
    Color mouseExitColor = new Color(51, 51, 51);

    DefaultTableModel model;

    String employeeName, today_date;

    public Dashboard() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_menu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_dashboard = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_viewIssuedGood = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbl_manageInventory = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_manageUsers = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbl_issueGood = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lbl_returnGood = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lbl_viewRecords = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lbl_logout = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lbl_defaulterList = new javax.swing.JLabel();
        panel_display = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_viewRecords = new rojerusan.RSTableMetro();
        j_date_From = new com.toedter.calendar.JDateChooser();
        btn_refresh = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        lbl_tot_profit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_tot_sales = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_sold_goods = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbo_assignee = new rojerusan.RSComboMetro();
        jLabel13 = new javax.swing.JLabel();
        cbo_products = new rojerusan.RSComboMetro();
        jLabel9 = new javax.swing.JLabel();
        txt_commission = new app.bolivia.swing.JCTextField();
        panel_load = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbltotalProfit = new javax.swing.JLabel();
        lbl_totCommission = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        genreceipt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnprint = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lbl_Cart = new javax.swing.JTextArea();
        lbl_clr_receipt = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        lbl_populateTable = new javax.swing.JLabel();
        lbl_calculated_commission = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        j_date_To = new com.toedter.calendar.JDateChooser();
        btn_populate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BLESSED SHOP");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 280, -1));

        lbl_close.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, 40));

        txtTime.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 180, 30));

        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 190, 30));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 5, 50));

        lbl_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        lbl_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 50));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel2.setText("Welcome, Admin");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        parentPanel.setLayout(null);

        panel_menu.setBackground(new java.awt.Color(51, 51, 51));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Features");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 60));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel5.setText("   Home Page");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 190, 30));

        panel_menu.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 60));

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dashboard.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_dashboard.setForeground(new java.awt.Color(153, 153, 153));
        lbl_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Library_32px.png"))); // NOI18N
        lbl_dashboard.setText("  Dashboard");
        lbl_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseExited(evt);
            }
        });
        jPanel6.add(lbl_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 210, 30));

        panel_menu.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, 60));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_viewIssuedGood.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lbl_viewIssuedGood.setForeground(new java.awt.Color(153, 153, 153));
        lbl_viewIssuedGood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        lbl_viewIssuedGood.setText("View Issued Goods");
        lbl_viewIssuedGood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewIssuedGoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewIssuedGoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewIssuedGoodMouseExited(evt);
            }
        });
        jPanel7.add(lbl_viewIssuedGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 240, 40));

        panel_menu.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 230, 60));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manageInventory.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 16)); // NOI18N
        lbl_manageInventory.setForeground(new java.awt.Color(153, 153, 153));
        lbl_manageInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        lbl_manageInventory.setText("Manage Inventory");
        lbl_manageInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_manageInventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_manageInventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_manageInventoryMouseExited(evt);
            }
        });
        jPanel8.add(lbl_manageInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 220, 40));

        panel_menu.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 230, 60));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manageUsers.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_manageUsers.setForeground(new java.awt.Color(153, 153, 153));
        lbl_manageUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        lbl_manageUsers.setText("  Manage Users");
        lbl_manageUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_manageUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_manageUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_manageUsersMouseExited(evt);
            }
        });
        jPanel9.add(lbl_manageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 30));

        panel_menu.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 60));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_issueGood.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_issueGood.setForeground(new java.awt.Color(153, 153, 153));
        lbl_issueGood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        lbl_issueGood.setText("  Issue Goods");
        lbl_issueGood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_issueGoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_issueGoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_issueGoodMouseExited(evt);
            }
        });
        jPanel10.add(lbl_issueGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 30));

        panel_menu.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 230, 60));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_returnGood.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_returnGood.setForeground(new java.awt.Color(153, 153, 153));
        lbl_returnGood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        lbl_returnGood.setText("  Return Goods");
        lbl_returnGood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_returnGoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_returnGoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_returnGoodMouseExited(evt);
            }
        });
        jPanel11.add(lbl_returnGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 30));

        panel_menu.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, 60));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_viewRecords.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_viewRecords.setForeground(new java.awt.Color(153, 153, 153));
        lbl_viewRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        lbl_viewRecords.setText("  View Records");
        lbl_viewRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewRecordsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewRecordsMouseExited(evt);
            }
        });
        jPanel12.add(lbl_viewRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 30));

        panel_menu.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 230, 60));

        jPanel14.setBackground(new java.awt.Color(153, 51, 0));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logout.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_logout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        lbl_logout.setText("  Log Out");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });
        jPanel14.add(lbl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 30));

        panel_menu.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 230, 60));

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_defaulterList.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_defaulterList.setForeground(new java.awt.Color(153, 153, 153));
        lbl_defaulterList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        lbl_defaulterList.setText("  Defaulter List");
        lbl_defaulterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseExited(evt);
            }
        });
        jPanel13.add(lbl_defaulterList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 30));

        panel_menu.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 230, 60));

        parentPanel.add(panel_menu);
        panel_menu.setBounds(0, 0, 230, 700);

        panel_display.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_viewRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assignee", "Product", "SoldQuantity", "Total Sales", "total_profit", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_viewRecords.setFuenteFilas(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbl_viewRecords.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbl_viewRecords.setFuenteHead(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbl_viewRecords.setRowHeight(14);
        jScrollPane1.setViewportView(tbl_viewRecords);

        panel_display.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 560, 540));

        j_date_From.setDateFormatString("EEEE, dd/MM/yyyy");
        j_date_From.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        j_date_From.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                j_date_FromPropertyChange(evt);
            }
        });
        panel_display.add(j_date_From, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 210, 30));

        btn_refresh.setBackground(new java.awt.Color(102, 255, 102));
        btn_refresh.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        panel_display.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 120, 25));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel12.setText("Total Profit:");
        panel_display.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 620, -1, -1));

        lbl_tot_profit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_tot_profit.setForeground(new java.awt.Color(0, 153, 153));
        panel_display.add(lbl_tot_profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 640, 80, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel7.setText("Total Sales:");
        panel_display.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, -1, -1));

        lbl_tot_sales.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_tot_sales.setForeground(new java.awt.Color(0, 153, 153));
        panel_display.add(lbl_tot_sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 640, 80, 40));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setText("No. Sold Goods:");
        panel_display.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 110, -1));

        lbl_sold_goods.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_sold_goods.setForeground(new java.awt.Color(0, 153, 153));
        panel_display.add(lbl_sold_goods, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 640, 80, 40));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setText("From Date:");
        panel_display.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel8.setText("Assignee:");
        jPanel15.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        cbo_assignee.setForeground(new java.awt.Color(0, 0, 0));
        cbo_assignee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Route" }));
        cbo_assignee.setColorBorde(new java.awt.Color(102, 102, 102));
        cbo_assignee.setColorFondo(new java.awt.Color(255, 153, 0));
        cbo_assignee.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbo_assignee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_assigneeActionPerformed(evt);
            }
        });
        jPanel15.add(cbo_assignee, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setText("Product Name:");
        jPanel15.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 120, -1));

        cbo_products.setForeground(new java.awt.Color(0, 0, 0));
        cbo_products.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        cbo_products.setColorBorde(new java.awt.Color(102, 102, 102));
        cbo_products.setColorFondo(new java.awt.Color(255, 153, 0));
        cbo_products.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbo_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_productsActionPerformed(evt);
            }
        });
        jPanel15.add(cbo_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 210, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setText("Commission:");
        jPanel15.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        txt_commission.setEditable(false);
        txt_commission.setText("\n");
        txt_commission.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_commission.setPlaceholder("Please enter Percentage Commision");
        jPanel15.add(txt_commission, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 60, -1));

        panel_load.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_load.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(204, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), new java.awt.Color(255, 255, 255)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setText("Total Profit:");
        jPanel17.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setText("Total Commission:");
        jPanel17.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lbltotalProfit.setBackground(new java.awt.Color(255, 255, 255));
        lbltotalProfit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbltotalProfit.setText("00.00");
        jPanel17.add(lbltotalProfit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 100, -1));

        lbl_totCommission.setBackground(new java.awt.Color(255, 255, 255));
        lbl_totCommission.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lbl_totCommission.setText("00.00");
        jPanel17.add(lbl_totCommission, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 100, 20));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 74));

        panel_load.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 270, 90));

        btnsubmit.setBackground(new java.awt.Color(204, 204, 0));
        btnsubmit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsubmit.setText("SUBMIT");
        btnsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsubmitMouseClicked(evt);
            }
        });
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        panel_load.add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        btnremove.setText("Remove");
        btnremove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnremoveMouseClicked(evt);
            }
        });
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });
        panel_load.add(btnremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        genreceipt.setText("Preview Payslip");
        genreceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genreceiptMouseClicked(evt);
            }
        });
        panel_load.add(genreceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 120, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Qty Sold", "Percentage Commission", "Total Profit", "Commission"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        panel_load.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 560, 190));

        btnprint.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnprint.setText("Print");
        btnprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprintMouseClicked(evt);
            }
        });
        panel_load.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        lbl_Cart.setColumns(20);
        lbl_Cart.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        lbl_Cart.setRows(20);
        jScrollPane3.setViewportView(lbl_Cart);

        panel_load.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 280, 350));

        lbl_clr_receipt.setBackground(new java.awt.Color(153, 153, 0));
        lbl_clr_receipt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_clr_receipt.setForeground(new java.awt.Color(0, 153, 0));
        lbl_clr_receipt.setText("CLEAR PREVIEW");
        lbl_clr_receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_clr_receiptMouseClicked(evt);
            }
        });
        panel_load.add(lbl_clr_receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 170, -1));

        jPanel15.add(panel_load, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 570, 590));

        jPanel18.setBackground(new java.awt.Color(51, 51, 51));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_populateTable.setBackground(new java.awt.Color(51, 51, 51));
        lbl_populateTable.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N
        lbl_populateTable.setForeground(new java.awt.Color(153, 255, 0));
        lbl_populateTable.setText("CLICK!! ADD TO TABLE");
        lbl_populateTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_populateTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lbl_populateTableFocusGained(evt);
            }
        });
        lbl_populateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_populateTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_populateTableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_populateTableMouseExited(evt);
            }
        });
        jPanel18.add(lbl_populateTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 20));

        jPanel15.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 30));

        lbl_calculated_commission.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel15.add(lbl_calculated_commission, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 120, 30));

        panel_display.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 690));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel6.setText("To Date:");
        panel_display.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        j_date_To.setDateFormatString("EEEE, dd/MM/yyyy");
        j_date_To.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        j_date_To.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                j_date_ToPropertyChange(evt);
            }
        });
        panel_display.add(j_date_To, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 200, 30));

        btn_populate.setBackground(new java.awt.Color(0, 255, 153));
        btn_populate.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        btn_populate.setText("Populate Table");
        btn_populate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_populateActionPerformed(evt);
            }
        });
        panel_display.add(btn_populate, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 150, 25));

        parentPanel.add(panel_display);
        panel_display.setBounds(230, 0, 1140, 700);

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1370, 700));

        setSize(new java.awt.Dimension(1366, 766));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void init() {
        Time.setTime(txtTime, txtDate);  // Calling the setTime method from the Time class

        loadEmployeeName();
    }

    //Load employee name into cbo_assignee combobox
    private void loadEmployeeName() {
        try {
            // Use DISTINCT to get unique employee names
            String query = "SELECT DISTINCT name FROM employee_details";
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(query);

            ResultSet rs = pst.executeQuery();

            cbo_assignee.removeAllItems();
            while (rs.next()) {
                cbo_assignee.addItem(rs.getString("name"));
            }

            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error loading employee names: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

//Load Product name into cbo_products combobox
    private void loadProducts() {
        cbo_products.removeAllItems();

        today_date = txtDate.getText();
        employeeName = (String) cbo_assignee.getSelectedItem();

//        This block of code first checks if employeeName in the combobox is empty
//        if (employeeName == null || employeeName.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Please select an employee.", "Warning", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
        try {
            // Use DISTINCT to get unique product names
            String query = "SELECT DISTINCT product_name FROM issued_goods WHERE employee_name = ?";
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, employeeName);

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cbo_products.addItem(rs.getString("product_name"));
            }

            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error loading products: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void retrieveCommission() {
        String selectedProduct = (String) cbo_products.getSelectedItem();

        if (selectedProduct == null || selectedProduct.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a product.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Establish connection to the database
            Connection con = DBConnection.getConnection();

            // Query to retrieve perc_commission for the selected product
            String sql = "SELECT perc_commission FROM products WHERE product_name = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, selectedProduct);

            // Execute the query
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                // Retrieve the commission percentage
                String percCommission = rs.getString("perc_commission");

                // Display the commission percentage or assign it to a relevant JLabel or JTextField
                txt_commission.setText(percCommission + "%");

                // Optionally, set the value to a MessageDialog instead
//            JOptionPane.showMessageDialog(this, "Commission Percentage: " + percCommission + "%", "Commission Info", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Handle case where no matching product is found
                JOptionPane.showMessageDialog(this, "No commission data found for the selected product.", "No Data", JOptionPane.WARNING_MESSAGE);
            }

            // Close resources
            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            // Handle exceptions
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error retrieving commission: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

//to pull the inventory details from the db to the table
    public void setPoductDetailsToTable() {

        try {
            Connection con = DBConnection.getConnection();

            // Get the current date from the JLabel in the desired format
            today_date = txtDate.getText();

            // Query to fetch data from the return_goods table
            String sql = "SELECT employee_name, product_name, qty_sold, total_price, total_profit, date FROM return_goods";

//            String sql = "SELECT * FROM return_goods WHERE date = ?";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();

            model = (DefaultTableModel) tbl_viewRecords.getModel();
            model.setRowCount(0); // Clear existing rows

            while (rs.next()) {
                Object[] row = {
                    rs.getString("employee_name"),
                    rs.getString("product_name"),
                    rs.getString("qty_sold"),
                    rs.getString("total_price"),
                    rs.getString("total_profit"),
                    rs.getString("date")
                };
                model.addRow(row);
            }

            // Close resources
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error retrieving data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void searchReturnGoods() {
        // Get selected values from comboboxes
        String assignee = (String) cbo_assignee.getSelectedItem();
        String product = (String) cbo_products.getSelectedItem();
        java.util.Date dateFrom = j_date_From.getDate();
        java.util.Date dateTo = j_date_To.getDate();

        // Date formatting
//        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy, EEEE");
//        String formattedDateFrom = (dateFrom != null) ? sdf.format(dateFrom) : null;
//        String formattedDateTo = (dateTo != null) ? sdf.format(dateTo) : null;
        // Convert java.util.Date to java.sql.Date
        java.sql.Date sqlDateFrom = (dateFrom != null) ? new java.sql.Date(dateFrom.getTime()) : null;
        java.sql.Date sqlDateTo = (dateTo != null) ? new java.sql.Date(dateTo.getTime()) : null;

        // Build the base SQL query
        StringBuilder query = new StringBuilder("SELECT * FROM return_goods WHERE 1=1");

        // Append conditions dynamically
        if (assignee != null && !assignee.isEmpty()) {
            query.append(" AND employee_name = ?");
        }
        if (product != null && !product.isEmpty()) {
            query.append(" AND product_name = ?");
        }
        if (sqlDateFrom != null) {
            query.append(" AND date >= ?");
        }
        if (sqlDateTo != null) {
            query.append(" AND date <= ?");
        }

        try {
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(query.toString());

            // Set parameters dynamically
            int index = 1;
            if (assignee != null && !assignee.isEmpty()) {
                pst.setString(index++, assignee);
            }
            if (product != null && !product.isEmpty()) {
                pst.setString(index++, product);
            }
            if (sqlDateFrom != null) {
                pst.setDate(index++, sqlDateFrom);
            }
            if (sqlDateTo != null) {
                pst.setDate(index++, sqlDateTo);
            }

            // Execute the query
            ResultSet rs = pst.executeQuery();

            // Clear existing table data
            DefaultTableModel model = (DefaultTableModel) tbl_viewRecords.getModel();
            model.setRowCount(0);

            // Populate the table with the result set
            while (rs.next()) {
                Object[] row = {
                    rs.getString("employee_name"),
                    rs.getString("product_name"),
                    rs.getString("qty_sold"),
                    rs.getString("total_price"),
                    rs.getString("total_profit"),
                    rs.getString("date")
                };
                model.addRow(row);
            }

            rs.close();
            pst.close();

            calculateAndDisplayTotalQuantitySold();
            calculateAndDisplayTotalSales();
            calculateAndDisplayTotalProfit();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Display the jTable to the jLabel
    private void calculateAndDisplayTotalQuantitySold() {
        // Initialize the sum
        int totalQuantitySold = 0;

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) tbl_viewRecords.getModel();

        // Iterate through the rows to sum up the values in column 3 (index 2, zero-based indexing)
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 2); // Column index for QuantitySold is 2

            // Ensure the value is not null and can be converted to an integer
            if (value != null) {
                try {
                    totalQuantitySold += Integer.parseInt(value.toString());
                } catch (NumberFormatException e) {
                    System.err.println("Error parsing quantity: " + value);
                }
            }
        }

        // Display the total on the label with formatting
        NumberFormat numberFormat = NumberFormat.getInstance();
        lbl_sold_goods.setText(numberFormat.format(totalQuantitySold));
    }

    // Display the jTable to the jLabel
    private void calculateAndDisplayTotalSales() {
        // Initialize the sum
        int totalSales = 0;

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) tbl_viewRecords.getModel();

        // Iterate through the rows to sum up the values in column 4 (index 3, zero-based indexing)
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 3); // Column index for TotalSales is 3

            // Ensure the value is not null and can be converted to an integer
            if (value != null) {
                try {
                    totalSales += Integer.parseInt(value.toString());
                } catch (NumberFormatException e) {
                    System.err.println("Error parsing quantity: " + value);
                }
            }
        }
        // Display the total on the label with formatting
        NumberFormat numberFormat = NumberFormat.getInstance();
        lbl_tot_sales.setText(numberFormat.format(totalSales));
    }

    // Display the jTable to the jLabel
    private void calculateAndDisplayTotalProfit() {
        // Initialize the sum
        int totalProfit = 0;

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) tbl_viewRecords.getModel();

        // Iterate through the rows to sum up the values in column 5 (index 4, zero-based indexing)
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 4); // Column index for TotalProfit is 4

            // Ensure the value is not null and can be converted to an integer
            if (value != null) {
                try {
                    totalProfit += Integer.parseInt(value.toString().replace(",", "").trim());
                } catch (NumberFormatException e) {
                    System.err.println("Error parsing quantity: " + value);
                }
            }
        }
        // Display the total on the label with formatting
        NumberFormat numberFormat = NumberFormat.getInstance();
        lbl_tot_profit.setText(numberFormat.format(totalProfit));
    }

    private void calculateCommission() {
        try {
            // Retrieve total profit from lbl_tot_profit
            String totalProfitText = lbl_tot_profit.getText();
// Parse the total profit to a numeric value
            double totalProfit = Double.parseDouble(lbl_tot_profit.getText().replace(",", "").trim());
            
            if (totalProfitText == null || totalProfitText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Total profit is not available.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Parse the total profit to a numeric value
//            double totalProfit = Double.parseDouble(totalProfitText.replace(",", "").trim());
            
//            int totalProfit = Integer.parseInt(totalProfitText.trim());

            // Retrieve percentage commission from txt_commission
            String commissionText = txt_commission.getText();
            if (commissionText == null || commissionText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Commission percentage is not set.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Remove the percentage sign and parse to a numeric value
            double commissionPercentage = Double.parseDouble(commissionText.replace("%", "").trim());

            // Calculate the commission
            double commission = (commissionPercentage / 100) * totalProfit;
            
//            double commission = (commissionPercentage / 100) * totalProfitText;

            // Display the calculated commission
//        lbl_calculated_commission.setText(String.format("Ksh %.2f", commission));
            lbl_calculated_commission.setText(String.format("%.2f", commission));

            // Optionally, you can log or display it elsewhere
//        JOptionPane.showMessageDialog(this, "Calculated Commission: Ksh " + String.format("%.2f", commission), "Commission Info", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException e) {
            // Handle parsing errors
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error in numeric conversion: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Handle other unexpected exceptions
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

//    Enters the data to the small jTable
    private void data_entry() {
        DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
        Vector v2 = new Vector();

        // v2.add(rs.getString("id"));
//        v2.add(txtfoodname.getText());
        v2.add(cbo_products.getSelectedItem());
        v2.add(lbl_sold_goods.getText());
        v2.add(txt_commission.getText());
        v2.add(lbl_tot_profit.getText());
        v2.add(lbl_calculated_commission.getText());

        d.addRow(v2);
    }

    // sums up the total commission and total profit
    public void new_data() {
        int sum = 0;
        double sumComm = 0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            
            sum += Integer.parseInt(jTable1.getValueAt(i, 3).toString().replace(",", "").trim());
            sumComm += Double.parseDouble(jTable1.getValueAt(i, 4).toString().replace(",", "").trim());
            
//            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
//            sumComm = sumComm + Double.parseDouble(jTable1.getValueAt(i, 4).toString());
        }

        lbltotalProfit.setText(Integer.toString(sum));
        lbl_totCommission.setText("Ksh. " + Double.toString(sumComm));

        lbl_calculated_commission.setText("");
        cbo_products.requestFocus();

    }
    
    private void my_cart(){
        lbl_Cart.setText(lbl_Cart.getText()+"======================================================================\n");
        lbl_Cart.setText(lbl_Cart.getText()+ "\t" +  "\t" + " \t BLESSING SHOP ENTERPRISE \n");
        lbl_Cart.setText(lbl_Cart.getText()+"  Payslip For:  " + employeeName +" \n");
        lbl_Cart.setText(lbl_Cart.getText()+"======================================================================\n");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); 
        lbl_Cart.setText(lbl_Cart.getText()
                +"Product Name       "+" | "+" Qty Sold "+"| "+" Percentage Commission "+"| "+" Commission "+"\n");
        lbl_Cart.setText(lbl_Cart.getText()+"\n");
        for(int i = 0; i < jTable1.getRowCount(); i++){
            String productName = jTable1.getValueAt(i, 0).toString();
            String qtySold = jTable1.getValueAt(i, 1).toString();
            String perc_comm = jTable1.getValueAt(i, 2).toString();
            String total_comm = jTable1.getValueAt(i, 4).toString();
            
            lbl_Cart.setText(lbl_Cart.getText()
                    +  productName  +   "\t" + "\t"   +  qtySold  +     "\t"  +  perc_comm  +    "\t"    +  total_comm +         "\n");
            
            lbl_Cart.setText(lbl_Cart.getText()+"\n"+"\n");
           
        }
        
        String grand_tot = lbl_totCommission.getText();
        
        //this gets Time & Date value
            String time_value = txtTime.getText(); // gets the current time
            String date_value = txtDate.getText(); // gets the current date
            
//        This gets the assignee name
        employeeName = (String) cbo_assignee.getSelectedItem();
        
        //        This gets the employer name
        String employerName = jLabel1.getText();

        
        
        lbl_Cart.setText(lbl_Cart.getText()+"\n");
        
        lbl_Cart.setText(lbl_Cart.getText()+"======================================================================\n");
         lbl_Cart.setText(lbl_Cart.getText()     + "Grand Total Commission   :  "   +   grand_tot  +     "\n"+"\n");
         
         
        lbl_Cart.setText(lbl_Cart.getText()+"======================================================================\n"+"\n");
        
        
        lbl_Cart.setText(lbl_Cart.getText()     + "Employer Name   :  "   +   employerName  +     "\n");
        
        lbl_Cart.setText(lbl_Cart.getText()     + "Assignee Name   :  "   +   employeeName  +     "\n"  +     "\n");
        
        
        lbl_Cart.setText(lbl_Cart.getText()+"======================================================================\n");
        lbl_Cart.setText(lbl_Cart.getText()     + "Generated at :  "      +   time_value  +     "\n"   + "\n" );
        lbl_Cart.setText(lbl_Cart.getText()     + "On DATE :   :  "   +   date_value  +     "\n");
        
        lbl_Cart.setText(lbl_Cart.getText()+"======================================================================\n");
        lbl_Cart.setText(lbl_Cart.getText()+" emmanuelsystems5@gmail.com   " + "\t" + "\t" +  "\t" + "  Copyright(c) 2024"+ "\n");
        lbl_Cart.setText(lbl_Cart.getText()+"======================================================================\n");
        
    }

    //clear the interface components
    private void clearComponents() {
        cbo_assignee.setSelectedIndex(0);
        cbo_products.setSelectedIndex(0);
        txt_commission.setText("");
        lbltotalProfit.setText("");
        lbl_totCommission.setText("");
        lbl_Cart.setText("");
        j_date_From.setDate(null);
        j_date_To.setDate(null);
    }


    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Close Application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void lbl_manageInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageInventoryMouseClicked

        ManageInventory inventory = new ManageInventory();
        inventory.setVisible(true);
        dispose();

//        Displaying only JPanels
//        JPanel panel_manageInventory = manageInventory.getPanel_manageInventory();
//
//        if (panel_menu.isVisible()) {
//
//            // Ensure panel_manageBooks is added to parentPanel
//            parentPanel.add(panel_manageInventory);
//            // Set panel_display to invisible
//            panel_display.setVisible(false);
//            // Set panel_manageBooks to visible
//            panel_manageInventory.setVisible(true);
//            // Set the bounds of panel_manageBooks to fill the entire parentPanel
//            panel_manageInventory.setBounds(250, 0, parentPanel.getWidth(), parentPanel.getHeight());
//
//        } else {
//            panel_menu.setVisible(true);
//            // Adjust panel_display when panel_menu reappears
//            panel_manageInventory.setBounds(panel_menu.getWidth(), 0, parentPanel.getWidth() - panel_menu.getWidth(), 700);
//
//        }
//
//        // Force panel_display to re-layout its components
//        parentPanel.repaint();

    }//GEN-LAST:event_lbl_manageInventoryMouseClicked

    private void lbl_manageInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageInventoryMouseEntered
        jPanel8.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_manageInventoryMouseEntered

    private void lbl_manageInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageInventoryMouseExited
        jPanel8.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_manageInventoryMouseExited

    private void lbl_manageUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageUsersMouseClicked
        ManageUsers users = new ManageUsers();
        users.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_manageUsersMouseClicked

    private void lbl_manageUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageUsersMouseEntered
        jPanel9.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_manageUsersMouseEntered

    private void lbl_manageUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageUsersMouseExited
        jPanel9.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_manageUsersMouseExited

    private void lbl_issueGoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_issueGoodMouseClicked
        IssueGoods issue = new IssueGoods();
        issue.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_issueGoodMouseClicked

    private void lbl_issueGoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_issueGoodMouseEntered
        jPanel10.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_issueGoodMouseEntered

    private void lbl_issueGoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_issueGoodMouseExited
        jPanel10.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_issueGoodMouseExited

    private void lbl_returnGoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnGoodMouseClicked
        ReturnGood ret = new ReturnGood();
        ret.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_returnGoodMouseClicked

    private void lbl_returnGoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnGoodMouseEntered
        jPanel11.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_returnGoodMouseEntered

    private void lbl_returnGoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnGoodMouseExited
        jPanel11.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_returnGoodMouseExited

    private void lbl_viewRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordsMouseClicked
        ViewAllRecords view = new ViewAllRecords();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_viewRecordsMouseClicked

    private void lbl_viewRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordsMouseEntered
        jPanel12.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_viewRecordsMouseEntered

    private void lbl_viewRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordsMouseExited
        jPanel12.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_viewRecordsMouseExited

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        LoginPage login = new LoginPage();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void lbl_defaulterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseClicked
        DefaulterList dl = new DefaulterList();
        dl.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_defaulterListMouseClicked

    private void lbl_defaulterListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseEntered
        jPanel13.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_defaulterListMouseEntered

    private void lbl_defaulterListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseExited
        jPanel13.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_defaulterListMouseExited

    private void lbl_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuMouseClicked

        if (panel_menu.isVisible()) {
            panel_menu.setVisible(false);
            // Adjust panel_display when panel_menu disappears
            panel_display.setBounds(0, 0, parentPanel.getWidth(), parentPanel.getHeight());

        } else {
            panel_menu.setVisible(true);
            // Adjust panel_display when panel_menu reappears
            panel_display.setBounds(panel_menu.getWidth(), 0, parentPanel.getWidth() - panel_menu.getWidth(), 700);

        }
        // Force panel_display to re-layout its components
        parentPanel.repaint();
    }//GEN-LAST:event_lbl_menuMouseClicked

    private void lbl_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseEntered
        jPanel6.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_dashboardMouseEntered

    private void lbl_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseExited
        jPanel6.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_dashboardMouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jPanel5.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jPanel5.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Home_page home = new Home_page();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void lbl_viewIssuedGoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssuedGoodMouseEntered
        // TODO add your handling code here:
        jPanel7.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_viewIssuedGoodMouseEntered

    private void lbl_viewIssuedGoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssuedGoodMouseExited
        // TODO add your handling code here:
        jPanel7.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_viewIssuedGoodMouseExited

    private void lbl_viewIssuedGoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssuedGoodMouseClicked
        // TODO add your handling code here:
        ViewIssuedGoodsDetails viewGoods = new ViewIssuedGoodsDetails();
        viewGoods.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_viewIssuedGoodMouseClicked

    private void cbo_assigneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_assigneeActionPerformed
        // TODO add your handling code here:
        loadProducts();
    }//GEN-LAST:event_cbo_assigneeActionPerformed

    private void cbo_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_productsActionPerformed

        if (cbo_products.getSelectedItem() != null) {
            retrieveCommission();
            setPoductDetailsToTable();
            searchReturnGoods();
        }
    }//GEN-LAST:event_cbo_productsActionPerformed

    private void j_date_FromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_j_date_FromPropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            searchReturnGoods();
        }
    }//GEN-LAST:event_j_date_FromPropertyChange

    private void j_date_ToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_j_date_ToPropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            searchReturnGoods();
        }
    }//GEN-LAST:event_j_date_ToPropertyChange

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        try{
            DefaultTableModel d =(DefaultTableModel) jTable1.getModel();
            //           int row = jTable1.getSelectedRow();
            d.setRowCount(0);
            //  d.removeRow(row);
        }catch (Exception e) {

        }
        
        clearComponents();

        setPoductDetailsToTable();

        calculateAndDisplayTotalQuantitySold();
        calculateAndDisplayTotalSales();
        calculateAndDisplayTotalProfit();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void lbl_clr_receiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clr_receiptMouseClicked
        // TODO add your handling code here:
        lbl_Cart.setText("");
    }//GEN-LAST:event_lbl_clr_receiptMouseClicked

    private void btnsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubmitMouseClicked

//        sales_pay();
    }//GEN-LAST:event_btnsubmitMouseClicked

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnremoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnremoveMouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
            //           int row = jTable1.getSelectedRow();
            d.setRowCount(0);
            //  d.removeRow(row);
        } catch (Exception e) {

        }
        new_data();
        lbl_Cart.setText("");

    }//GEN-LAST:event_btnremoveMouseClicked

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        try {
            DefaultTableModel d = (DefaultTableModel) jTable1.getModel();
            //           int row = jTable1.getSelectedRow();
            d.setRowCount(0);
            //  d.removeRow(row);
        } catch (Exception e) {

        }
        lbl_Cart.setText("");
    }//GEN-LAST:event_btnremoveActionPerformed

    private void genreceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genreceiptMouseClicked

        lbl_Cart.setText("");
        
        my_cart();
    }//GEN-LAST:event_genreceiptMouseClicked

    private void btnprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprintMouseClicked

        try {
            lbl_Cart.print();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnprintMouseClicked

    private void btn_populateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_populateActionPerformed

        setPoductDetailsToTable();

        calculateAndDisplayTotalQuantitySold();
        calculateAndDisplayTotalSales();
        calculateAndDisplayTotalProfit();
    }//GEN-LAST:event_btn_populateActionPerformed

    private void lbl_populateTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_populateTableMouseEntered
        jPanel18.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_populateTableMouseEntered

    private void lbl_populateTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbl_populateTableFocusGained
        jPanel18.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_populateTableFocusGained

    private void lbl_populateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_populateTableMouseClicked
        // TODO add your handling code here:
        calculateCommission();
        data_entry();
        new_data();
    }//GEN-LAST:event_lbl_populateTableMouseClicked

    private void lbl_populateTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_populateTableMouseExited
        jPanel18.setBackground(mouseExitColor);        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_populateTableMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_populate;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnsubmit;
    private rojerusan.RSComboMetro cbo_assignee;
    private rojerusan.RSComboMetro cbo_products;
    private javax.swing.JButton genreceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser j_date_From;
    private com.toedter.calendar.JDateChooser j_date_To;
    private javax.swing.JTextArea lbl_Cart;
    private javax.swing.JLabel lbl_calculated_commission;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_clr_receipt;
    private javax.swing.JLabel lbl_dashboard;
    private javax.swing.JLabel lbl_defaulterList;
    private javax.swing.JLabel lbl_issueGood;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_manageInventory;
    private javax.swing.JLabel lbl_manageUsers;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JLabel lbl_populateTable;
    private javax.swing.JLabel lbl_returnGood;
    private javax.swing.JLabel lbl_sold_goods;
    private javax.swing.JLabel lbl_totCommission;
    private javax.swing.JLabel lbl_tot_profit;
    private javax.swing.JLabel lbl_tot_sales;
    private javax.swing.JLabel lbl_viewIssuedGood;
    private javax.swing.JLabel lbl_viewRecords;
    private javax.swing.JLabel lbltotalProfit;
    private javax.swing.JPanel panel_display;
    private javax.swing.JPanel panel_load;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel parentPanel;
    private rojerusan.RSTableMetro tbl_viewRecords;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtTime;
    private app.bolivia.swing.JCTextField txt_commission;
    // End of variables declaration//GEN-END:variables
}
