/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

//import MiniFrames.*;
import default_package.DBConnection;
import default_package.Time;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lenovo-x130
 */
public class IssueGoods extends javax.swing.JFrame {
//    Initialize components

    ManageInventory manageInventory = new ManageInventory();

    // Gets the window's screen position
    int xx, xy;

    //Global variable for Hover Effect
    Color mouseEnterColor = new Color(255, 153, 0);
    Color mouseExitColor = new Color(51, 51, 51);
    
    DefaultTableModel model;
    
    String employeeName, productName, pricePerProduct, qty, total, today_date;

    public IssueGoods() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_menu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_homePage = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_dashboard = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_viewIssuedGood = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbl_manageInventory = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_manageUsers = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbl_issueGood = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lbl_returnGood = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lbl_viewRecords = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lbl_logout = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lbl_defaulterList = new javax.swing.JLabel();
        panel_display = new javax.swing.JPanel();
        cbo_products = new rojerusan.RSComboMetro();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tot_price = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        cbo_assignee = new rojerusan.RSComboMetro();
        jLabel10 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTodayInventory = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_issued_goods = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                IssueGoods.this.windowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BLESSED SHOP");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 280, -1));

        lbl_close.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, 40));

        txtTime.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 180, 30));

        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 210, 30));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 5, 50));

        lbl_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        lbl_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 50));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel2.setText("Welcome, Admin");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        parentPanel.setLayout(null);

        panel_menu.setBackground(new java.awt.Color(51, 51, 51));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Features");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 60));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_homePage.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_homePage.setForeground(new java.awt.Color(153, 153, 153));
        lbl_homePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        lbl_homePage.setText("   Home Page");
        lbl_homePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homePageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_homePageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_homePageMouseExited(evt);
            }
        });
        jPanel5.add(lbl_homePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 60));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dashboard.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_dashboard.setForeground(new java.awt.Color(153, 153, 153));
        lbl_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Library_32px.png"))); // NOI18N
        lbl_dashboard.setText("  Dashboard");
        lbl_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseExited(evt);
            }
        });
        jPanel6.add(lbl_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, 60));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_viewIssuedGood.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_viewIssuedGood.setForeground(new java.awt.Color(153, 153, 153));
        lbl_viewIssuedGood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        lbl_viewIssuedGood.setText("View Issued Goods");
        lbl_viewIssuedGood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewIssuedGoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewIssuedGoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewIssuedGoodMouseExited(evt);
            }
        });
        jPanel7.add(lbl_viewIssuedGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 240, 40));

        panel_menu.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 250, 60));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manageInventory.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_manageInventory.setForeground(new java.awt.Color(153, 153, 153));
        lbl_manageInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        lbl_manageInventory.setText("Manage Inventory");
        lbl_manageInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_manageInventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_manageInventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_manageInventoryMouseExited(evt);
            }
        });
        jPanel8.add(lbl_manageInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 240, 40));

        panel_menu.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 60));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manageUsers.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_manageUsers.setForeground(new java.awt.Color(153, 153, 153));
        lbl_manageUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        lbl_manageUsers.setText("  Manage Users");
        lbl_manageUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_manageUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_manageUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_manageUsersMouseExited(evt);
            }
        });
        jPanel9.add(lbl_manageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 60));

        jPanel10.setBackground(new java.awt.Color(255, 153, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_issueGood.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_issueGood.setForeground(new java.awt.Color(153, 153, 153));
        lbl_issueGood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        lbl_issueGood.setText("  Issue Goods");
        jPanel10.add(lbl_issueGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 250, 60));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_returnGood.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_returnGood.setForeground(new java.awt.Color(153, 153, 153));
        lbl_returnGood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        lbl_returnGood.setText("  Return Goods");
        lbl_returnGood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_returnGoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_returnGoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_returnGoodMouseExited(evt);
            }
        });
        jPanel11.add(lbl_returnGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 60));

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_viewRecords.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_viewRecords.setForeground(new java.awt.Color(153, 153, 153));
        lbl_viewRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        lbl_viewRecords.setText("  View Records");
        lbl_viewRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewRecordsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewRecordsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewRecordsMouseExited(evt);
            }
        });
        jPanel12.add(lbl_viewRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 250, 60));

        jPanel14.setBackground(new java.awt.Color(153, 51, 0));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logout.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_logout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        lbl_logout.setText("  Log Out");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });
        jPanel14.add(lbl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 250, 60));

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_defaulterList.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_defaulterList.setForeground(new java.awt.Color(153, 153, 153));
        lbl_defaulterList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        lbl_defaulterList.setText("  Defaulter List");
        lbl_defaulterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseExited(evt);
            }
        });
        jPanel13.add(lbl_defaulterList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 250, 60));

        parentPanel.add(panel_menu);
        panel_menu.setBounds(0, 0, 250, 700);

        panel_display.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbo_products.setForeground(new java.awt.Color(0, 0, 0));
        cbo_products.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        cbo_products.setColorBorde(new java.awt.Color(102, 102, 102));
        cbo_products.setColorFondo(new java.awt.Color(255, 153, 0));
        cbo_products.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbo_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_productsActionPerformed(evt);
            }
        });
        panel_display.add(cbo_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 280, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Product:");
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panel_display.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Price per Product:");
        panel_display.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, 30));

        txtprice.setEditable(false);
        txtprice.setBackground(new java.awt.Color(255, 255, 255));
        txtprice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtprice.setForeground(new java.awt.Color(0, 102, 102));
        txtprice.setText("00.00");
        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpriceKeyTyped(evt);
            }
        });
        panel_display.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 160, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Total Price:");
        panel_display.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 170, 30));

        tot_price.setEditable(false);
        tot_price.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        tot_price.setForeground(new java.awt.Color(0, 102, 102));
        panel_display.add(tot_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 160, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Quantity To Give:");
        panel_display.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 170, 30));

        txtQty.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtQty.setText("0");
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyKeyTyped(evt);
            }
        });
        panel_display.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 160, 30));

        cbo_assignee.setForeground(new java.awt.Color(0, 0, 0));
        cbo_assignee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Route" }));
        cbo_assignee.setColorBorde(new java.awt.Color(102, 102, 102));
        cbo_assignee.setColorFondo(new java.awt.Color(255, 153, 0));
        cbo_assignee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        panel_display.add(cbo_assignee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 280, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Assignee:");
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panel_display.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        btnSave.setBackground(new java.awt.Color(102, 255, 102));
        btnSave.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnSave.setText("SAVE CHANGES");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panel_display.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 160, -1));

        btnUpdate.setBackground(new java.awt.Color(0, 204, 204));
        btnUpdate.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnUpdate.setText("UPDATE ENTRIES");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        panel_display.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 160, -1));

        btnDelete.setBackground(new java.awt.Color(255, 51, 0));
        btnDelete.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnDelete.setText("DELETE ENTRIES");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        panel_display.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 160, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Today's Inventory:");
        panel_display.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, 30));

        txtTodayInventory.setEditable(false);
        txtTodayInventory.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtTodayInventory.setText("0");
        txtTodayInventory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTodayInventoryKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTodayInventoryKeyTyped(evt);
            }
        });
        panel_display.add(txtTodayInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 160, 30));

        tbl_issued_goods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assignee", "Product", "PricePerProduct", "QuantityReceived", "TotalPrice", "Date"
            }
        ));
        tbl_issued_goods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_issued_goodsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_issued_goods);

        panel_display.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 2, 790, 430));

        parentPanel.add(panel_display);
        panel_display.setBounds(250, 0, 1120, 700);

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1370, 700));

        setSize(new java.awt.Dimension(1366, 766));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void init() {
        Time.setTime(txtTime, txtDate);  // Calling the setTime method from the Time class
//        loadProducts();
        loadEmployeeName();
        // Delay the loading of the PRODUCTS COMBO BOX to ensure txtDate is initialized
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                loadProducts();
            }
        });
        timer.setRepeats(false); // Only execute once
        timer.start();
    }

    
    //Load Product name into cbo_products combobox
    private void loadProducts() {
        try {
            Connection con = DBConnection.getConnection();
            
            // Get the current date from the JLabel in the desired format
            String today_date = txtDate.getText();
            
            String sql = "SELECT product_name FROM inventory where date = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, today_date);

            ResultSet rs = pst.executeQuery();
            pst.setString(1, today_date);

            while (rs.next()) {
                String productName = rs.getString("product_name");
                cbo_products.addItem(productName);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    //Load employee name into cbo_assignee combobox
    private void loadEmployeeName() {
        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT name FROM employee_details";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String employeeName = rs.getString("name");
                cbo_assignee.addItem(employeeName);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

// Get product price from the database
    private void fetchProductPrice(String productName) {
        // Get the current date from the JLabel in the desired format
        String today = txtDate.getText();
        try {
            Connection con = DBConnection.getConnection();
            //String sql = "SELECT price_per_product && total_qty FROM inventory WHERE product_name = ?";
            String sql = "SELECT price_per_product, total_qty FROM inventory WHERE product_name = ? AND date = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, productName);
            pst.setString(2, today);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txtprice.setText(rs.getString("price_per_product"));
                //txtTodayInventory
                txtTodayInventory.setText(rs.getString("total_qty"));
            } else {
                txtprice.setText("");
                txtTodayInventory.setText("0");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    //    To calculate the product of Inventory
    private void pro_total() {

        Integer a = Integer.parseInt(txtprice.getText());
        Integer b = Integer.parseInt(txtQty.getText());

        Integer tot;

        tot = a * b;

        tot_price.setText(String.valueOf(tot));
    }

    // Checks the value entered at 'txtQty' should not exceed value at 'txtTodayInventory'
     private void checkQuantity() {
        try {
            int quantity = Integer.parseInt(txtQty.getText());
            int inventory = Integer.parseInt(txtTodayInventory.getText());

            if (quantity > inventory) {
                JOptionPane.showMessageDialog(null, "Quantity to issue should not exceed Today's inventory quantity");
                txtQty.setText("0");
            }
        } catch (NumberFormatException e) {
            // Handle the case where the input is not a valid integer
            e.printStackTrace();
        
        }
    }
     
     //method to clear jtable before adding new data on it
    public void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_issued_goods.getModel();
        model.setRowCount(0);
    }
    
    //to pull the inventory details from the db to the table
    public void setPoductDetailsToTable() {

        try {
            Connection con = DBConnection.getConnection();

            // Get the current date from the JLabel in the desired format
            String today_date = txtDate.getText();

            String sql = "SELECT * FROM issued_goods WHERE date = ?";
            PreparedStatement st = con.prepareStatement(sql);
            st.setString(1, today_date);

            ResultSet rs = st.executeQuery();
            st.setString(1, today_date);

            while (rs.next()) {
//                String productName, pricePerProduct, qty, qtyBal, total, today_date;
                String employeeName = rs.getString("employee_name");
                String productName = rs.getString("product_name");
                String pricePerProduct = rs.getString("price_per_product");
                String qty = rs.getString("qty_given");
                String total = rs.getString("total_price");
                String t_date = rs.getString("date");

                Object[] obj = {employeeName, productName, pricePerProduct, qty, total, t_date};
                model = (DefaultTableModel) tbl_issued_goods.getModel();
                //adds a row array
                model.addRow(obj);
            }

            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    
    //to add products to the database in issued_goods table
    public boolean addProduct() {

        boolean isAdded = false;

        employeeName = (String) cbo_assignee.getSelectedItem();
        productName = (String) cbo_products.getSelectedItem();
        pricePerProduct = txtprice.getText();
        qty = txtQty.getText();
        total = tot_price.getText();
        today_date = txtDate.getText();

        try {
            // Parse quantity fields to integers
            int qtyIssued = Integer.parseInt(qty);
            
            //checks for duplicate entry using product name and today's date
//            checkduplicate();
            Connection con = DBConnection.getConnection();

            // Check for duplicates
            String checkSql = "SELECT COUNT(*) FROM issued_goods WHERE employee_name = ? AND product_name = ? AND date = ?";
            PreparedStatement checkPst = con.prepareStatement(checkSql);
            checkPst.setString(1, employeeName);
            checkPst.setString(2, productName);
            checkPst.setString(3, today_date);
            ResultSet rs = checkPst.executeQuery();
            rs.next();
            int count = rs.getInt(1);

            if (count > 0) {
                JOptionPane.showMessageDialog(null, "Already issued this product on this day for this Assignee");
                clearComponents();
                return isAdded;
            }

            String sql = "insert into issued_goods (employee_name, product_name, price_per_product, qty_given,"
                    + " total_price, date) values(?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);

            //sets the values from the textfield to the colums in the db
            pst.setString(1, employeeName);
            pst.setString(2, productName);
            pst.setString(3, pricePerProduct);
            pst.setInt(4, qtyIssued);
            pst.setString(5, total);
            pst.setString(6, today_date);

            //If a database row is added to output a success message
            int rowCount = pst.executeUpdate();

            if (rowCount > 0) {
                isAdded = true;
            } else {
                isAdded = false;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        //returns the 'isAdded' variable value
        return isAdded;

    }

    //method to Update the product details
    public boolean updateProduct() {

        // Get the current date from the JLabel in the desired format
        String today = txtDate.getText();

        boolean isUpdated = false;

        employeeName = (String) cbo_assignee.getSelectedItem();
        productName = (String) cbo_products.getSelectedItem();
        pricePerProduct = txtprice.getText();
        qty = txtQty.getText();
        total = tot_price.getText();
//        today_date = txtDate.getText();

        try {
            // Parse quantity fields to integers
            int qtyVal = Integer.parseInt(qty);
            int totalPrice = Integer.parseInt(total);

            Connection con = DBConnection.getConnection();
            String sql = "update issued_goods set employee_name = ?, product_name = ?, price_per_product = ?, qty_given = ?,"
                    + " total_price = ? where employee_name = ? AND product_name = ? AND date = ?";
            PreparedStatement pst = con.prepareStatement(sql);

            //sets the values from the textfield to the colums in the db
            pst.setString(1, employeeName);
            pst.setString(2, productName);
            pst.setString(3, pricePerProduct);
            pst.setInt(4, qtyVal);
            pst.setInt(5, totalPrice);
            
            pst.setString(6, employeeName);
            pst.setString(7, productName);
            pst.setString(8, today);

            //If a database row is added to output a success message
            int rowCount = pst.executeUpdate();

            if (rowCount > 0) {
                isUpdated = true;
            } else {
                isUpdated = false;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        //returns the 'isAdded' variable value
        return isUpdated;

    }

    //method to delete products details
    public boolean deleteProduct() {

        boolean isDeleted = false;

        productName = (String) cbo_products.getSelectedItem();
        employeeName = (String) cbo_assignee.getSelectedItem();

        try {
            Connection con = DBConnection.getConnection();
            String sql = "delete from issued_goods where employee_name = ? AND product_name = ?";
            PreparedStatement pst = con.prepareStatement(sql);

            //sets the values from the textfield to the colums in the db
            // Set both parameters
            pst.setString(1, employeeName);
            pst.setString(2, productName);

            //If a database row is added to output a success message
            int rowCount = pst.executeUpdate();

            if (rowCount > 0) {
                isDeleted = true;
            } else {
                isDeleted = false;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        //returns the 'isAdded' variable value
        return isDeleted;
    }

    //clear the interface components
    private void clearComponents() {

        cbo_assignee.setSelectedIndex(0);
        cbo_products.setSelectedIndex(0);
        txtTodayInventory.setText("0");
        txtprice.setText("00.00");
        txtQty.setText("0");
        tot_price.setText("");
    }
    
    
    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Close Application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void lbl_viewIssuedGoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssuedGoodMouseClicked
        ViewIssuedGoodsDetails viewIssued = new ViewIssuedGoodsDetails();
        viewIssued.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_viewIssuedGoodMouseClicked

    private void lbl_viewIssuedGoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssuedGoodMouseEntered
        jPanel7.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_viewIssuedGoodMouseEntered

    private void lbl_viewIssuedGoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssuedGoodMouseExited
        jPanel7.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_viewIssuedGoodMouseExited

    private void lbl_manageInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageInventoryMouseClicked

        ManageInventory inventory = new ManageInventory();
        inventory.setVisible(true);
        dispose();

    }//GEN-LAST:event_lbl_manageInventoryMouseClicked

    private void lbl_manageInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageInventoryMouseEntered
        jPanel8.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_manageInventoryMouseEntered

    private void lbl_manageInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageInventoryMouseExited
        jPanel8.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_manageInventoryMouseExited

    private void lbl_manageUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageUsersMouseClicked
        ManageUsers users = new ManageUsers();
        users.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_manageUsersMouseClicked

    private void lbl_manageUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageUsersMouseEntered
        jPanel9.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_manageUsersMouseEntered

    private void lbl_manageUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageUsersMouseExited
        jPanel9.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_manageUsersMouseExited

    private void lbl_returnGoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnGoodMouseClicked
        ReturnGood ret = new ReturnGood();
        ret.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_returnGoodMouseClicked

    private void lbl_returnGoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnGoodMouseEntered
        jPanel11.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_returnGoodMouseEntered

    private void lbl_returnGoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnGoodMouseExited
        jPanel11.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_returnGoodMouseExited

    private void lbl_viewRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordsMouseClicked
        ViewAllRecords view = new ViewAllRecords();
        view.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_viewRecordsMouseClicked

    private void lbl_viewRecordsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordsMouseEntered
        jPanel12.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_viewRecordsMouseEntered

    private void lbl_viewRecordsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordsMouseExited
        jPanel12.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_viewRecordsMouseExited

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        LoginPage login = new LoginPage();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void lbl_defaulterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseClicked
        DefaulterList dl = new DefaulterList();
        dl.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_defaulterListMouseClicked

    private void lbl_defaulterListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseEntered
        jPanel13.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_defaulterListMouseEntered

    private void lbl_defaulterListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseExited
        jPanel13.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_defaulterListMouseExited

    private void lbl_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuMouseClicked

        if (panel_menu.isVisible()) {
            panel_menu.setVisible(false);
            // Adjust panel_display when panel_menu disappears
            panel_display.setBounds(0, 0, parentPanel.getWidth(), parentPanel.getHeight());

        } else {
            panel_menu.setVisible(true);
            // Adjust panel_display when panel_menu reappears
            panel_display.setBounds(panel_menu.getWidth(), 0, parentPanel.getWidth() - panel_menu.getWidth(), 700);

        }
        // Force panel_display to re-layout its components
        parentPanel.repaint();
    }//GEN-LAST:event_lbl_menuMouseClicked

    private void lbl_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseEntered
        jPanel6.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_dashboardMouseEntered

    private void lbl_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseExited
        jPanel6.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_dashboardMouseExited

    private void lbl_homePageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homePageMouseEntered
        jPanel5.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_homePageMouseEntered

    private void lbl_homePageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homePageMouseExited
        jPanel5.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_homePageMouseExited

    private void lbl_homePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homePageMouseClicked
        Home_page home = new Home_page();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_homePageMouseClicked

    private void cbo_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_productsActionPerformed
        String selectedProduct = (String) cbo_products.getSelectedItem();
        if (selectedProduct != null) {
            fetchProductPrice(selectedProduct);
        }
    }//GEN-LAST:event_cbo_productsActionPerformed

    private void txtpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtpriceKeyTyped

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        checkQuantity();
        pro_total();
    }//GEN-LAST:event_txtQtyKeyReleased

    private void txtQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQtyKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtQty.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the quantity to issue field");

        } else if (cbo_products.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select a Product");

        } else if (addProduct() == true) {
            JOptionPane.showMessageDialog(this, "Product Issued Successfully...");

            clearTable();
            setPoductDetailsToTable();
            clearComponents();
        } else {
            JOptionPane.showMessageDialog(this, "Product Issue failed, Please check your Database Connection...");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (txtQty.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the issue quantity field");

        } else if (cbo_products.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select a Product");

        } else if (updateProduct() == true) {
            JOptionPane.showMessageDialog(this, "Product Issue Updated Successfully...");

            clearTable();
            setPoductDetailsToTable();
            clearComponents();
        } else {
            JOptionPane.showMessageDialog(this, "Issued Goods Updated failed, Please check your Database Connection...");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (cbo_products.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please select the name of the product you want to delete");

        } else if (deleteProduct() == true) {
            JOptionPane.showMessageDialog(this, "Issued Goods Deleted Successfully...");

            clearTable();
            setPoductDetailsToTable();
            clearComponents();
        } else {
            JOptionPane.showMessageDialog(this, "Issued Goods Delete failed, Please check your Database Connection...");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtTodayInventoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTodayInventoryKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTodayInventoryKeyReleased

    private void txtTodayInventoryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTodayInventoryKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTodayInventoryKeyTyped

    //delays to populate the jtable for 1000ms to wait for txtDate to be initialized
    private void windowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowActivated
        clearTable();
        // Delay the loading of the table to ensure txtDate is initialized
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                setPoductDetailsToTable();
            }
        });
        timer.setRepeats(false); // Only execute once
        timer.start();
    }//GEN-LAST:event_windowActivated

    private void tbl_issued_goodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_issued_goodsMouseClicked
        int rowNo = tbl_issued_goods.getSelectedRow();
        TableModel model = tbl_issued_goods.getModel();

        cbo_assignee.setSelectedItem(model.getValueAt(rowNo, 0).toString());
        cbo_products.setSelectedItem(model.getValueAt(rowNo, 1).toString());
        txtprice.setText(model.getValueAt(rowNo, 2).toString());
        txtQty.setText(model.getValueAt(rowNo, 3).toString());
        tot_price.setText(model.getValueAt(rowNo, 4).toString());
    }//GEN-LAST:event_tbl_issued_goodsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueGoods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private rojerusan.RSComboMetro cbo_assignee;
    private rojerusan.RSComboMetro cbo_products;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_dashboard;
    private javax.swing.JLabel lbl_defaulterList;
    private javax.swing.JLabel lbl_homePage;
    private javax.swing.JLabel lbl_issueGood;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_manageInventory;
    private javax.swing.JLabel lbl_manageUsers;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JLabel lbl_returnGood;
    private javax.swing.JLabel lbl_viewIssuedGood;
    private javax.swing.JLabel lbl_viewRecords;
    private javax.swing.JPanel panel_display;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel parentPanel;
    private rojerusan.RSTableMetro tbl_issued_goods;
    private javax.swing.JTextField tot_price;
    private javax.swing.JLabel txtDate;
    private javax.swing.JTextField txtQty;
    private javax.swing.JLabel txtTime;
    private javax.swing.JTextField txtTodayInventory;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
