/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

//import MiniFrames.*;
import default_package.DBConnection;
import default_package.Time;
import java.awt.Color;
import java.sql.*;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo-x130
 */
public class ViewAllRecords extends javax.swing.JFrame {
//    Initialize components

    ManageInventory manageInventory = new ManageInventory();

    // Gets the window's screen position
    int xx, xy;

    //Global variable for Hover Effect
    Color mouseEnterColor = new Color(255, 153, 0);
    Color mouseExitColor = new Color(51, 51, 51);

    DefaultTableModel model;

    String employeeName, productName, pricePerProduct, todayInventory, qty, soldProducts, total, total_profit, today_date;

    public ViewAllRecords() {
        initComponents();
        init();
        setPoductDetailsToTable();
        
        calculateAndDisplayTotalQuantityReceived();
        calculateAndDisplayTotalQuantitySold();
        calculateAndDisplayTotalSales();
        calculateAndDisplayTotalProfit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_menu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_dashboard = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbl_viewIssuedGood = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lbl_manageInventory = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_manageUsers = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbl_issueGood = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lbl_returnGood = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lbl_viewRecords = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lbl_logout = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lbl_defaulterList = new javax.swing.JLabel();
        panel_display = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbo_assignee = new rojerusan.RSComboMetro();
        jLabel6 = new javax.swing.JLabel();
        cbo_products = new rojerusan.RSComboMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_viewRecords = new rojerusan.RSTableMetro();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        j_date_From = new com.toedter.calendar.JDateChooser();
        j_date_To = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_sold_goods = new javax.swing.JLabel();
        lbl_received_qty = new javax.swing.JLabel();
        lbl_tot_sales = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_tot_profit = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BLESSED SHOP");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 280, -1));

        lbl_close.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(255, 255, 255));
        lbl_close.setText("X");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, 40));

        txtTime.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 180, 30));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 5, 50));

        lbl_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        lbl_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_menuMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 50));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel2.setText("Welcome, Admin");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, -1, -1));

        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        parentPanel.setLayout(null);

        panel_menu.setBackground(new java.awt.Color(51, 51, 51));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Features");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 220, 60));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel5.setText("   Home Page");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 190, 30));

        panel_menu.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 60));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dashboard.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_dashboard.setForeground(new java.awt.Color(153, 153, 153));
        lbl_dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Library_32px.png"))); // NOI18N
        lbl_dashboard.setText("  Dashboard");
        lbl_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_dashboardMouseExited(evt);
            }
        });
        jPanel6.add(lbl_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 250, 60));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_viewIssuedGood.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_viewIssuedGood.setForeground(new java.awt.Color(153, 153, 153));
        lbl_viewIssuedGood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        lbl_viewIssuedGood.setText("View Issued Goods");
        lbl_viewIssuedGood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewIssuedGoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewIssuedGoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewIssuedGoodMouseExited(evt);
            }
        });
        jPanel7.add(lbl_viewIssuedGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 240, 40));

        panel_menu.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 250, 60));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manageInventory.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_manageInventory.setForeground(new java.awt.Color(153, 153, 153));
        lbl_manageInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_List_of_Thumbnails_50px.png"))); // NOI18N
        lbl_manageInventory.setText("Manage Inventory");
        lbl_manageInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_manageInventoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_manageInventoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_manageInventoryMouseExited(evt);
            }
        });
        jPanel8.add(lbl_manageInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 240, 40));

        panel_menu.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 60));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manageUsers.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_manageUsers.setForeground(new java.awt.Color(153, 153, 153));
        lbl_manageUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Read_Online_26px.png"))); // NOI18N
        lbl_manageUsers.setText("  Manage Users");
        lbl_manageUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_manageUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_manageUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_manageUsersMouseExited(evt);
            }
        });
        jPanel9.add(lbl_manageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, 60));

        jPanel10.setBackground(new java.awt.Color(51, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_issueGood.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_issueGood.setForeground(new java.awt.Color(153, 153, 153));
        lbl_issueGood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Sell_26px.png"))); // NOI18N
        lbl_issueGood.setText("  Issue Goods");
        lbl_issueGood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_issueGoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_issueGoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_issueGoodMouseExited(evt);
            }
        });
        jPanel10.add(lbl_issueGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 250, 60));

        jPanel11.setBackground(new java.awt.Color(51, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_returnGood.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_returnGood.setForeground(new java.awt.Color(153, 153, 153));
        lbl_returnGood.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Return_Purchase_26px.png"))); // NOI18N
        lbl_returnGood.setText("  Return Goods");
        lbl_returnGood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_returnGoodMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_returnGoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_returnGoodMouseExited(evt);
            }
        });
        jPanel11.add(lbl_returnGood, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 60));

        jPanel12.setBackground(new java.awt.Color(255, 153, 0));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_viewRecords.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_viewRecords.setForeground(new java.awt.Color(153, 153, 153));
        lbl_viewRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_View_Details_26px.png"))); // NOI18N
        lbl_viewRecords.setText("  View Records");
        jPanel12.add(lbl_viewRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 250, 60));

        jPanel14.setBackground(new java.awt.Color(153, 51, 0));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logout.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_logout.setForeground(new java.awt.Color(255, 255, 255));
        lbl_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        lbl_logout.setText("  Log Out");
        lbl_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_logoutMouseClicked(evt);
            }
        });
        jPanel14.add(lbl_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 250, 60));

        jPanel13.setBackground(new java.awt.Color(51, 51, 51));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_defaulterList.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        lbl_defaulterList.setForeground(new java.awt.Color(153, 153, 153));
        lbl_defaulterList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/adminIcons/icons8_Conference_26px.png"))); // NOI18N
        lbl_defaulterList.setText("  Defaulter List");
        lbl_defaulterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseExited(evt);
            }
        });
        jPanel13.add(lbl_defaulterList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, 230, 30));

        panel_menu.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 250, 60));

        parentPanel.add(panel_menu);
        panel_menu.setBounds(0, 0, 250, 700);

        panel_display.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Assignee:");
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panel_display.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 30));

        cbo_assignee.setForeground(new java.awt.Color(0, 0, 0));
        cbo_assignee.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Route" }));
        cbo_assignee.setColorBorde(new java.awt.Color(102, 102, 102));
        cbo_assignee.setColorFondo(new java.awt.Color(255, 153, 0));
        cbo_assignee.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbo_assignee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_assigneeActionPerformed(evt);
            }
        });
        panel_display.add(cbo_assignee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 280, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("To Date:");
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panel_display.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 120, 30));

        cbo_products.setForeground(new java.awt.Color(0, 0, 0));
        cbo_products.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        cbo_products.setColorBorde(new java.awt.Color(102, 102, 102));
        cbo_products.setColorFondo(new java.awt.Color(255, 153, 0));
        cbo_products.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbo_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_productsActionPerformed(evt);
            }
        });
        panel_display.add(cbo_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 280, -1));

        tbl_viewRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assignee", "Product", "PricePerProduct", "QuantityReceived", "ReturnedQuantity", "SoldQuantity", "Total Sales", "total_profit", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_viewRecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_viewRecordsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_viewRecords);

        panel_display.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1100, 520));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setText("Quantity Received:");
        panel_display.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setText("Total Sales:");
        panel_display.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, -1, -1));

        j_date_From.setDateFormatString("yyyy-MM-dd");
        j_date_From.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        j_date_From.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                j_date_FromPropertyChange(evt);
            }
        });
        panel_display.add(j_date_From, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 230, 30));

        j_date_To.setDateFormatString("yyyy-MM-dd");
        j_date_To.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        j_date_To.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                j_date_ToPropertyChange(evt);
            }
        });
        panel_display.add(j_date_To, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 220, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Product:");
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panel_display.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 120, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("From Date:");
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        panel_display.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 120, 30));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setText("No. Sold Goods:");
        panel_display.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, -1, -1));

        lbl_sold_goods.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        lbl_sold_goods.setForeground(new java.awt.Color(0, 153, 153));
        panel_display.add(lbl_sold_goods, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, 90, 40));

        lbl_received_qty.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        lbl_received_qty.setForeground(new java.awt.Color(0, 153, 153));
        panel_display.add(lbl_received_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, 110, 40));

        lbl_tot_sales.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        lbl_tot_sales.setForeground(new java.awt.Color(0, 153, 153));
        panel_display.add(lbl_tot_sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 650, 90, 40));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel12.setText("Total Profit:");
        panel_display.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 620, -1, -1));

        lbl_tot_profit.setFont(new java.awt.Font("Times New Roman", 1, 23)); // NOI18N
        lbl_tot_profit.setForeground(new java.awt.Color(0, 153, 153));
        panel_display.add(lbl_tot_profit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 650, 80, 40));

        btn_refresh.setBackground(new java.awt.Color(102, 255, 102));
        btn_refresh.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        panel_display.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 120, 30));

        parentPanel.add(panel_display);
        panel_display.setBounds(250, 0, 1120, 700);

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1370, 700));

        setSize(new java.awt.Dimension(1366, 766));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void init() {
        Time.setTime(txtTime, txtDate);  // Calling the setTime method from the Time class

        loadEmployeeName();
//        loadProducts();
    }

    //to pull the inventory details from the db to the table
    public void setPoductDetailsToTable() {

        try {
            Connection con = DBConnection.getConnection();

            // Get the current date from the JLabel in the desired format
            today_date = txtDate.getText();

            // Query to fetch data from the return_goods table
            String sql = "SELECT employee_name, product_name, price_per_product, received_qty, qty_returned, qty_sold, total_price, total_profit, date FROM return_goods";

//            String sql = "SELECT * FROM return_goods WHERE date = ?";
            PreparedStatement st = con.prepareStatement(sql);
            ResultSet rs = st.executeQuery();

            model = (DefaultTableModel) tbl_viewRecords.getModel();
            model.setRowCount(0); // Clear existing rows

            while (rs.next()) {
                Object[] row = {
                    rs.getString("employee_name"),
                    rs.getString("product_name"),
                    rs.getString("price_per_product"),
                    rs.getString("received_qty"),
                    rs.getString("qty_returned"),
                    rs.getString("qty_sold"),
                    rs.getString("total_price"),
                    rs.getString("total_profit"),
                    rs.getString("date")
                };
                model.addRow(row);
            }

            // Close resources
            rs.close();
            st.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error retrieving data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

//Load Product name into cbo_products combobox
    private void loadProducts() {
        cbo_products.removeAllItems();

        today_date = txtDate.getText();
        employeeName = (String) cbo_assignee.getSelectedItem();

//        This block of code first checks if employeeName in the combobox is empty
//        if (employeeName == null || employeeName.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Please select an employee.", "Warning", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
        try {
            // Use DISTINCT to get unique product names
            String query = "SELECT DISTINCT product_name FROM issued_goods WHERE employee_name = ?";
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, employeeName);

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                cbo_products.addItem(rs.getString("product_name"));
            }

            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error loading products: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    //Load employee name into cbo_assignee combobox
    private void loadEmployeeName() {
        try {
            // Use DISTINCT to get unique employee names
            String query = "SELECT DISTINCT name FROM employee_details";
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(query);

            ResultSet rs = pst.executeQuery();

            cbo_assignee.removeAllItems();
            while (rs.next()) {
                cbo_assignee.addItem(rs.getString("name"));
            }

            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error loading employee names: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
       
    }

    private void searchReturnGoods() {
        // Get selected values from comboboxes
        String assignee = (String) cbo_assignee.getSelectedItem();
        String product = (String) cbo_products.getSelectedItem();
        java.util.Date dateFrom = j_date_From.getDate();
        java.util.Date dateTo = j_date_To.getDate();

        // Date formatting
//        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy, EEEE");
//        String formattedDateFrom = (dateFrom != null) ? sdf.format(dateFrom) : null;
//        String formattedDateTo = (dateTo != null) ? sdf.format(dateTo) : null;

  // Convert java.util.Date to java.sql.Date
    java.sql.Date sqlDateFrom = (dateFrom != null) ? new java.sql.Date(dateFrom.getTime()) : null;
    java.sql.Date sqlDateTo = (dateTo != null) ? new java.sql.Date(dateTo.getTime()) : null;
    
        // Build the base SQL query
        StringBuilder query = new StringBuilder("SELECT * FROM return_goods WHERE 1=1");

        // Append conditions dynamically
        if (assignee != null && !assignee.isEmpty()) {
            query.append(" AND employee_name = ?");
        }
        if (product != null && !product.isEmpty()) {
            query.append(" AND product_name = ?");
        }
        if (sqlDateFrom != null) {
            query.append(" AND date >= ?");
        }
        if (sqlDateTo != null) {
            query.append(" AND date <= ?");
        }

        try {
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement(query.toString());

            // Set parameters dynamically
            int index = 1;
            if (assignee != null && !assignee.isEmpty()) {
                pst.setString(index++, assignee);
            }
            if (product != null && !product.isEmpty()) {
                pst.setString(index++, product);
            }
            if (sqlDateFrom != null) {
                pst.setDate(index++, sqlDateFrom);
            }
            if (sqlDateTo != null) {
                pst.setDate(index++, sqlDateTo);
            }

            // Execute the query
            ResultSet rs = pst.executeQuery();

            // Clear existing table data
            DefaultTableModel model = (DefaultTableModel) tbl_viewRecords.getModel();
            model.setRowCount(0);

            // Populate the table with the result set
            while (rs.next()) {
                Object[] row = {
                    rs.getString("employee_name"),
                    rs.getString("product_name"),
                    rs.getString("price_per_product"),
                    rs.getString("received_qty"),
                    rs.getString("qty_returned"),
                    rs.getString("qty_sold"),
                    rs.getString("total_price"),
                    rs.getString("total_profit"),
                    rs.getString("date")
                };
                model.addRow(row);
            }

            rs.close();
            pst.close();

            calculateAndDisplayTotalQuantityReceived();
            calculateAndDisplayTotalQuantitySold();
            calculateAndDisplayTotalSales();
            calculateAndDisplayTotalProfit();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Display the jTable to the jLabel
    private void calculateAndDisplayTotalQuantityReceived() {
        // Initialize the sum
        int totalQuantityReceived = 0;

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) tbl_viewRecords.getModel();

        // Iterate through the rows to sum up the values in column 4 (index 3, zero-based indexing)
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 3); // Column index for QuantityReceived is 3

            // Ensure the value is not null and can be converted to an integer
            if (value != null) {
                try {
                    totalQuantityReceived += Integer.parseInt(value.toString());
                } catch (NumberFormatException e) {
                    System.err.println("Error parsing quantity: " + value);
                }
            }
        }

        // Display the total on the label with formatting
        NumberFormat numberFormat = NumberFormat.getInstance();
        lbl_received_qty.setText(numberFormat.format(totalQuantityReceived));
    }

    // Display the jTable to the jLabel
    private void calculateAndDisplayTotalQuantitySold() {
        // Initialize the sum
        int totalQuantitySold = 0;

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) tbl_viewRecords.getModel();

        // Iterate through the rows to sum up the values in column 4 (index 3, zero-based indexing)
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 5); // Column index for QuantityReceived is 3

            // Ensure the value is not null and can be converted to an integer
            if (value != null) {
                try {
                    totalQuantitySold += Integer.parseInt(value.toString());
                } catch (NumberFormatException e) {
                    System.err.println("Error parsing quantity: " + value);
                }
            }
        }

        // Display the total on the label with formatting
        NumberFormat numberFormat = NumberFormat.getInstance();
        lbl_sold_goods.setText(numberFormat.format(totalQuantitySold));
    }

    // Display the jTable to the jLabel
    private void calculateAndDisplayTotalSales() {
        // Initialize the sum
        int totalSales = 0;

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) tbl_viewRecords.getModel();

        // Iterate through the rows to sum up the values in column 4 (index 3, zero-based indexing)
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 6); // Column index for QuantityReceived is 3

            // Ensure the value is not null and can be converted to an integer
            if (value != null) {
                try {
                    totalSales += Integer.parseInt(value.toString());
                } catch (NumberFormatException e) {
                    System.err.println("Error parsing quantity: " + value);
                }
            }
        }
        // Display the total on the label with formatting
        NumberFormat numberFormat = NumberFormat.getInstance();
        lbl_tot_sales.setText(numberFormat.format(totalSales));
    }

    // Display the jTable to the jLabel
    private void calculateAndDisplayTotalProfit() {
        // Initialize the sum
        int totalProfit = 0;

        // Get the table model
        DefaultTableModel model = (DefaultTableModel) tbl_viewRecords.getModel();

        // Iterate through the rows to sum up the values in column 4 (index 3, zero-based indexing)
        for (int i = 0; i < model.getRowCount(); i++) {
            Object value = model.getValueAt(i, 7); // Column index for QuantityReceived is 3

            // Ensure the value is not null and can be converted to an integer
            if (value != null) {
                try {
                    totalProfit += Integer.parseInt(value.toString());
                } catch (NumberFormatException e) {
                    System.err.println("Error parsing quantity: " + value);
                }
            }
        }
        // Display the total on the label with formatting
        NumberFormat numberFormat = NumberFormat.getInstance();
        lbl_tot_profit.setText(numberFormat.format(totalProfit));
    }

    //clear the interface components
    private void clearComponents() {
        cbo_assignee.setSelectedIndex(0);
        cbo_products.setSelectedIndex(0);
        j_date_From.setDate(null);
        j_date_To.setDate(null);
    }

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Close Application?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void lbl_viewIssuedGoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssuedGoodMouseClicked
        ViewIssuedGoodsDetails viewIssued = new ViewIssuedGoodsDetails();
        viewIssued.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_viewIssuedGoodMouseClicked

    private void lbl_viewIssuedGoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssuedGoodMouseEntered
        jPanel7.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_viewIssuedGoodMouseEntered

    private void lbl_viewIssuedGoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewIssuedGoodMouseExited
        jPanel7.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_viewIssuedGoodMouseExited

    private void lbl_manageInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageInventoryMouseClicked

        ManageInventory inventory = new ManageInventory();
        inventory.setVisible(true);
        dispose();

    }//GEN-LAST:event_lbl_manageInventoryMouseClicked

    private void lbl_manageInventoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageInventoryMouseEntered
        jPanel8.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_manageInventoryMouseEntered

    private void lbl_manageInventoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageInventoryMouseExited
        jPanel8.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_manageInventoryMouseExited

    private void lbl_manageUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageUsersMouseClicked
        ManageUsers users = new ManageUsers();
        users.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_manageUsersMouseClicked

    private void lbl_manageUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageUsersMouseEntered
        jPanel9.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_manageUsersMouseEntered

    private void lbl_manageUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageUsersMouseExited
        jPanel9.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_manageUsersMouseExited

    private void lbl_issueGoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_issueGoodMouseClicked
        IssueGoods issue = new IssueGoods();
        issue.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_issueGoodMouseClicked

    private void lbl_issueGoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_issueGoodMouseEntered
        jPanel10.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_issueGoodMouseEntered

    private void lbl_issueGoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_issueGoodMouseExited
        jPanel10.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_issueGoodMouseExited

    private void lbl_returnGoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnGoodMouseClicked
        ReturnGood ret = new ReturnGood();
        ret.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_returnGoodMouseClicked

    private void lbl_returnGoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnGoodMouseEntered
        jPanel11.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_returnGoodMouseEntered

    private void lbl_returnGoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_returnGoodMouseExited
        jPanel11.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_returnGoodMouseExited

    private void lbl_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_logoutMouseClicked
        LoginPage login = new LoginPage();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_logoutMouseClicked

    private void lbl_defaulterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseClicked
        DefaulterList dl = new DefaulterList();
        dl.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_defaulterListMouseClicked

    private void lbl_defaulterListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseEntered
        jPanel13.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_defaulterListMouseEntered

    private void lbl_defaulterListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseExited
        jPanel13.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_defaulterListMouseExited

    private void lbl_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_menuMouseClicked

        if (panel_menu.isVisible()) {
            panel_menu.setVisible(false);
            // Adjust panel_display when panel_menu disappears
            panel_display.setBounds(0, 0, parentPanel.getWidth(), parentPanel.getHeight());

        } else {
            panel_menu.setVisible(true);
            // Adjust panel_display when panel_menu reappears
            panel_display.setBounds(panel_menu.getWidth(), 0, parentPanel.getWidth() - panel_menu.getWidth(), 700);

        }
        // Force panel_display to re-layout its components
        parentPanel.repaint();
    }//GEN-LAST:event_lbl_menuMouseClicked

    private void lbl_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseEntered
        jPanel6.setBackground(mouseEnterColor);
    }//GEN-LAST:event_lbl_dashboardMouseEntered

    private void lbl_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseExited
        jPanel6.setBackground(mouseExitColor);
    }//GEN-LAST:event_lbl_dashboardMouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jPanel5.setBackground(mouseEnterColor);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jPanel5.setBackground(mouseExitColor);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Home_page home = new Home_page();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void cbo_assigneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_assigneeActionPerformed
        // TODO add your handling code here:
        loadProducts();
    }//GEN-LAST:event_cbo_assigneeActionPerformed

    private void cbo_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_productsActionPerformed

        if (cbo_products.getSelectedItem() != null) {
//            fetchProductPrice(selectedProduct);
            searchReturnGoods();
        }
    }//GEN-LAST:event_cbo_productsActionPerformed

    private void tbl_viewRecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_viewRecordsMouseClicked
//        int rowNo = tbl_return_goods.getSelectedRow();
//        TableModel model = tbl_return_goods.getModel();
//
//        cbo_assignee.setSelectedItem(model.getValueAt(rowNo, 0).toString());
//        cbo_products.setSelectedItem(model.getValueAt(rowNo, 1).toString());
//        txtprice.setText(model.getValueAt(rowNo, 2).toString());
//        txtQty.setText(model.getValueAt(rowNo, 3).toString());
//        tot_price.setText(model.getValueAt(rowNo, 4).toString());
    }//GEN-LAST:event_tbl_viewRecordsMouseClicked

    private void j_date_FromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_j_date_FromPropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            searchReturnGoods();
        }
    }//GEN-LAST:event_j_date_FromPropertyChange

    private void j_date_ToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_j_date_ToPropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            searchReturnGoods();
        }
    }//GEN-LAST:event_j_date_ToPropertyChange

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        clearComponents();
        setPoductDetailsToTable();

        calculateAndDisplayTotalQuantityReceived();
        calculateAndDisplayTotalQuantitySold();
        calculateAndDisplayTotalSales();
        calculateAndDisplayTotalProfit();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void lbl_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_dashboardMouseClicked
        // TODO add your handling code here:
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_dashboardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_refresh;
    private rojerusan.RSComboMetro cbo_assignee;
    private rojerusan.RSComboMetro cbo_products;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser j_date_From;
    private com.toedter.calendar.JDateChooser j_date_To;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_dashboard;
    private javax.swing.JLabel lbl_defaulterList;
    private javax.swing.JLabel lbl_issueGood;
    private javax.swing.JLabel lbl_logout;
    private javax.swing.JLabel lbl_manageInventory;
    private javax.swing.JLabel lbl_manageUsers;
    private javax.swing.JLabel lbl_menu;
    private javax.swing.JLabel lbl_received_qty;
    private javax.swing.JLabel lbl_returnGood;
    private javax.swing.JLabel lbl_sold_goods;
    private javax.swing.JLabel lbl_tot_profit;
    private javax.swing.JLabel lbl_tot_sales;
    private javax.swing.JLabel lbl_viewIssuedGood;
    private javax.swing.JLabel lbl_viewRecords;
    private javax.swing.JPanel panel_display;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel parentPanel;
    private rojerusan.RSTableMetro tbl_viewRecords;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
