package MiniFrames;

import default_package.DBConnection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;

/**
 *
 * @author Lenovo-x130
 */
public class MiniFrame_addProduct extends javax.swing.JFrame {

    String productName, productPrice;
    private JPopupMenu suggestionMenu;

    /**
     * Creates new form addProduct
     */
    public MiniFrame_addProduct() {
        initComponents();
        suggestionMenu = new JPopupMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_productName = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_productPrice = new javax.swing.JTextField();
        btnDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(142, 163, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_back.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbl_back.setForeground(new java.awt.Color(255, 255, 255));
        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        lbl_back.setText("Back");
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_backMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 50));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("ADD NEW PRODUCT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 280, 50));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Description of the Product: ");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 250, 30));

        txt_productName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_productName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_productNameKeyReleased(evt);
            }
        });
        jPanel1.add(txt_productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 260, 40));

        btnSubmit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 120, 30));

        btnUpdate.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 120, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("Price of the Product: ");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 250, 30));

        txt_productPrice.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_productPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_productPriceKeyTyped(evt);
            }
        });
        jPanel1.add(txt_productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 260, 40));

        btnDel.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        btnDel.setText("DELETE");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jPanel1.add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 260));

        setSize(new java.awt.Dimension(596, 259));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // On Key Typed show suggestions
    private void showSuggestions(String text) {
        ArrayList<String> suggestions = getSuggestions(text);

        if (suggestions.isEmpty()) {
            suggestionMenu.setVisible(false);
            return;
        }

        suggestionMenu.removeAll();
        for (String suggestion : suggestions) {
            JMenuItem item = new JMenuItem(suggestion);
            item.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    txt_productName.setText(suggestion);
                    suggestionMenu.setVisible(false);
                }
            });
            suggestionMenu.add(item);
        }

        suggestionMenu.show(txt_productName, 0, txt_productName.getHeight());
        suggestionMenu.setVisible(true);
    }

    private ArrayList<String> getSuggestions(String text) {
        ArrayList<String> suggestions = new ArrayList<>();
        try {
            Connection con = DBConnection.getConnection();
            String sql = "SELECT product_name FROM products WHERE product_name LIKE ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, text + "%");
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                suggestions.add(rs.getString("product_name"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return suggestions;
    }

    //to add products to the database in student_details table
    public boolean addProduct() {

        boolean isAdded = false;

        productName = txt_productName.getText();
        productPrice = txt_productPrice.getText();

        try {

            Connection con = DBConnection.getConnection();
            String sql = "insert into products (product_name, price) values(?,?)";
            PreparedStatement pst = con.prepareStatement(sql);

            //sets the values from the textfield to the colums in the db
            pst.setString(1, productName);
            pst.setString(2, productPrice);

            //If a database row is added to output a success message
            int rowCount = pst.executeUpdate();

            if (rowCount > 0) {
                isAdded = true;
            } else {
                isAdded = false;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        //returns the 'isAdded' variable value
        return isAdded;

    }

    //method to Update the product details
    public boolean updateProduct() {

        boolean isUpdated = false;

        productName = txt_productName.getText();
        productPrice = txt_productPrice.getText();

        try {
            Connection con = DBConnection.getConnection();
            String sql = "update products set product_name = ?, price = ? where product_name = ?";
            PreparedStatement pst = con.prepareStatement(sql);

            //sets the values from the textfield to the colums in the db
            pst.setString(1, productName);
            pst.setString(2, productPrice);
            pst.setString(3, productName);

            //If a database row is added to output a success message
            int rowCount = pst.executeUpdate();

            if (rowCount > 0) {
                isUpdated = true;
            } else {
                isUpdated = false;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        //returns the 'isAdded' variable value
        return isUpdated;

    }
    
    //method to delete products details
    public boolean deleteProduct() {

        boolean isDeleted = false;

//        studentId = Integer.parseInt(txt_studentId.getText());
        productName = txt_productName.getText();

        try {
            Connection con = DBConnection.getConnection();
            String sql = "delete from products where product_name = ?";
            PreparedStatement pst = con.prepareStatement(sql);

            //sets the values from the textfield to the colums in the db
            pst.setString(1, productName);

            //If a database row is added to output a success message
            int rowCount = pst.executeUpdate();

            if (rowCount > 0) {
                isDeleted = true;
            } else {
                isDeleted = false;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        //returns the 'isAdded' variable value
        return isDeleted;
    }

    private void clearComponents() {
        txt_productName.setText("");
        txt_productPrice.setText("");
    }
    
    private void lbl_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_backMouseClicked

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        if (txt_productName.getText().isEmpty() || txt_productPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all the fields");

        } else if (addProduct() == true) {
            JOptionPane.showMessageDialog(this, "Product Added Successfully...");

            clearComponents();
        } else {
            JOptionPane.showMessageDialog(this, "Product Addition failed, Please check your Database Connection...");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //updateProduct()
        if (txt_productName.getText().isEmpty() || txt_productPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill all the fields");

        } else if (updateProduct() == true) {
            JOptionPane.showMessageDialog(this, "Product Updated Successfully...");

            clearComponents();
        } else {
            JOptionPane.showMessageDialog(this, "Product Update failed, Please check your Database Connection...");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txt_productPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_productPriceKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_productPriceKeyTyped

    private void txt_productNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_productNameKeyReleased
        String text = txt_productName.getText();
        if (!text.isEmpty()) {
            showSuggestions(text);
        } else {
            suggestionMenu.setVisible(false);
        }
    }//GEN-LAST:event_txt_productNameKeyReleased

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        if (txt_productName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the name of the product you want to delete");

        } else if (deleteProduct() == true) {
            JOptionPane.showMessageDialog(this, "Product Deleted Successfully...");

            clearComponents();
        } else {
            JOptionPane.showMessageDialog(this, "Product Delete failed, Please check your Database Connection...");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniFrame_addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniFrame_addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniFrame_addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniFrame_addProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniFrame_addProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JTextField txt_productName;
    private javax.swing.JTextField txt_productPrice;
    // End of variables declaration//GEN-END:variables
}
